apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retester
  namespace: prow-monitoring
  labels:
    app: prow
    component: retester
    prow-app: retester
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - ci
  selector:
    matchLabels:
      app: prow
      component: retester
